# Generated by Django 2.1.4 on 2019-10-08 01:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_user_id', models.CharField(blank=True, max_length=40)),
                ('box_folder_id', models.CharField(blank=True, max_length=40)),
                ('user', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
