# Generated by Django 2.1.4 on 2019-10-08 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_file_id', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('SUB', 'Submitted'), ('PEND', 'Pending'), ('APP', 'Approved'), ('COMP', 'Complete')], default='SUB', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
