# Generated by Django 2.1.4 on 2019-10-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20191008_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
